-- AlterTable
ALTER TABLE "business_attributes" ALTER COLUMN "accepts_insurance" DROP NOT NULL,
ALTER COLUMN "accepts_insurance" DROP DEFAULT,
ALTER COLUMN "accepts_insurance" SET DATA TYPE TEXT,
ALTER COLUMN "byob" DROP NOT NULL,
ALTER COLUMN "byob" DROP DEFAULT,
ALTER COLUMN "byob" SET DATA TYPE TEXT,
ALTER COLUMN "bike_parking" DROP NOT NULL,
ALTER COLUMN "bike_parking" DROP DEFAULT,
ALTER COLUMN "bike_parking" SET DATA TYPE TEXT,
ALTER COLUMN "business_accepts_bitcoin" DROP NOT NULL,
ALTER COLUMN "business_accepts_bitcoin" DROP DEFAULT,
ALTER COLUMN "business_accepts_bitcoin" SET DATA TYPE TEXT,
ALTER COLUMN "business_accepts_credit_cards" DROP NOT NULL,
ALTER COLUMN "business_accepts_credit_cards" DROP DEFAULT,
ALTER COLUMN "business_accepts_credit_cards" SET DATA TYPE TEXT,
ALTER COLUMN "by_appointment_only" DROP NOT NULL,
ALTER COLUMN "by_appointment_only" DROP DEFAULT,
ALTER COLUMN "by_appointment_only" SET DATA TYPE TEXT,
ALTER COLUMN "caters" DROP NOT NULL,
ALTER COLUMN "caters" DROP DEFAULT,
ALTER COLUMN "caters" SET DATA TYPE TEXT,
ALTER COLUMN "coat_check" DROP NOT NULL,
ALTER COLUMN "coat_check" DROP DEFAULT,
ALTER COLUMN "coat_check" SET DATA TYPE TEXT,
ALTER COLUMN "corkage" DROP NOT NULL,
ALTER COLUMN "corkage" DROP DEFAULT,
ALTER COLUMN "corkage" SET DATA TYPE TEXT,
ALTER COLUMN "dogs_allowed" DROP NOT NULL,
ALTER COLUMN "dogs_allowed" DROP DEFAULT,
ALTER COLUMN "dogs_allowed" SET DATA TYPE TEXT,
ALTER COLUMN "drive_thru" DROP NOT NULL,
ALTER COLUMN "drive_thru" DROP DEFAULT,
ALTER COLUMN "drive_thru" SET DATA TYPE TEXT,
ALTER COLUMN "good_for_dancing" DROP NOT NULL,
ALTER COLUMN "good_for_dancing" DROP DEFAULT,
ALTER COLUMN "good_for_dancing" SET DATA TYPE TEXT,
ALTER COLUMN "good_for_kids" DROP NOT NULL,
ALTER COLUMN "good_for_kids" DROP DEFAULT,
ALTER COLUMN "good_for_kids" SET DATA TYPE TEXT,
ALTER COLUMN "happy_hour" DROP NOT NULL,
ALTER COLUMN "happy_hour" DROP DEFAULT,
ALTER COLUMN "happy_hour" SET DATA TYPE TEXT,
ALTER COLUMN "has_tv" DROP NOT NULL,
ALTER COLUMN "has_tv" DROP DEFAULT,
ALTER COLUMN "has_tv" SET DATA TYPE TEXT,
ALTER COLUMN "outdooor_seating" DROP NOT NULL,
ALTER COLUMN "outdooor_seating" DROP DEFAULT,
ALTER COLUMN "outdooor_seating" SET DATA TYPE TEXT,
ALTER COLUMN "restaurant_delivery" DROP NOT NULL,
ALTER COLUMN "restaurant_delivery" DROP DEFAULT,
ALTER COLUMN "restaurant_delivery" SET DATA TYPE TEXT,
ALTER COLUMN "restaurant_good_for_groups" DROP NOT NULL,
ALTER COLUMN "restaurant_good_for_groups" DROP DEFAULT,
ALTER COLUMN "restaurant_good_for_groups" SET DATA TYPE TEXT,
ALTER COLUMN "restaurant_reservations" DROP NOT NULL,
ALTER COLUMN "restaurant_reservations" DROP DEFAULT,
ALTER COLUMN "restaurant_reservations" SET DATA TYPE TEXT,
ALTER COLUMN "restaurant_table_service" DROP NOT NULL,
ALTER COLUMN "restaurant_table_service" DROP DEFAULT,
ALTER COLUMN "restaurant_table_service" SET DATA TYPE TEXT,
ALTER COLUMN "restaurant_take_out" DROP NOT NULL,
ALTER COLUMN "restaurant_take_out" DROP DEFAULT,
ALTER COLUMN "restaurant_take_out" SET DATA TYPE TEXT,
ALTER COLUMN "wheelchair_accessible" DROP NOT NULL,
ALTER COLUMN "wheelchair_accessible" DROP DEFAULT,
ALTER COLUMN "wheelchair_accessible" SET DATA TYPE TEXT;
